const elements = [
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 1],
        [0, 0, 0],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 1,
      type: "village",
      shape: [
        [1, 1, 0],
        [0, 1, 1],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 1],
        [0, 0, 1],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 1],
        [0, 0, 1],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 1],
        [0, 1, 0],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 1],
        [0, 1, 0],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 1,
      type: "village",
      shape: [
        [1, 1, 0],
        [1, 0, 0],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 1,
      type: "village",
      shape: [
        [1, 1, 1],
        [1, 1, 0],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 1,
      type: "village",
      shape: [
        [1, 1, 0],
        [0, 1, 1],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 1,
      type: "village",
      shape: [
        [0, 1, 0],
        [1, 1, 1],
        [0, 1, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 1],
        [1, 0, 0],
        [1, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 0, 0],
        [1, 1, 1],
        [1, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 0],
        [0, 1, 1],
        [0, 0, 1],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 0],
        [0, 1, 1],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
    {
      time: 2,
      type: "village",
      shape: [
        [1, 1, 0],
        [1, 1, 0],
        [0, 0, 0],
      ],
      rotation: 0,
      mirrored: false,
    },
  ]; // village ONLY